name: "Docker Build & Push"
description: "Builds a Docker image and pushes it to a container registry"
inputs:
  app:
    description: "Application to build"
    required: true
  dockerfile:
    description: "Dockerfile to build"
    required: false
    default: "Dockerfile"
  context:
    description: "Docker build context"
    required: false
    default: "."
  tag:
    description: "Docker image tag"
    required: false
    default: "${{ github.sha }}"
  registry_address:
    description: "Container registry address"
    required: true
  registry_username:
    description: "Container registry username"
    required: true
  registry_password:
    description: "Container registry password"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      shell: bash
      run: |
        docker build \
          --tag ${{ inputs.registry_address }}/${{ inputs.app }}:${{ inputs.tag }} \
          --file ${{ inputs.dockerfile }} \
          ${{ inputs.context }}

    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry_address }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}
        logout: false

    - name: Push image to registry
      shell: bash
      run: docker push "${{ inputs.registry_address }}/${{ inputs.app }}:${{ inputs.tag }}"
