name: "Docker Build & Push"
description: "Builds a Docker image and pushes it to a container registry"
inputs:
  app:
    description: "Application to build"
    required: true
  dockerfile:
    description: "Dockerfile to build"
    required: false
    default: "Dockerfile"
  dockerignore_override:
    description: "Override default .dockerignore file from context"
    required: false
  context:
    description: "Docker build context"
    required: false
    default: "."
  tag:
    description: "Docker image tag"
    required: false
    default: "${{ github.sha }}"
  directory:
    description: "Directory to change into before building"
    required: false
    default: "."
  args:
    description: "Additional 'docker build' arguments"
    required: false
    default: ""
  registry_address:
    description: "Container registry address"
    required: true
  registry_username:
    description: "Container registry username"
    required: true
  registry_password:
    description: "Container registry password"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Display build information
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        echo "::group::Docker Build Configuration"
        echo "[INFO] Image Details"
        echo "[INFO]  • Full image name: ${{ inputs.registry_address }}/${{ inputs.app }}:${{ inputs.tag }}"
        echo "[INFO]  • Application:     ${{ inputs.app }}"
        echo "[INFO]  • Registry:        ${{ inputs.registry_address }}"
        echo "[INFO]  • Tag:             ${{ inputs.tag }}"
        echo ""
        echo "[INFO] Build Context"
        echo "[INFO]  • Dockerfile:      ${{ inputs.dockerfile }}"
        echo "[INFO]  • Context path:    ${{ inputs.context }}"
        echo "[INFO]  • Working dir:     ${{ inputs.directory }}"
        echo "[INFO]  • Build args:      ${{ inputs.args }}"
        echo "[INFO]  • Dockerignore:    ${{ inputs.dockerignore_override || 'default' }}"
        echo "::endgroup::"

    - name: Configure .dockerignore override
      if: inputs.dockerignore_override != ''
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        cp "${{ inputs.context }}/.dockerignore" "${{ inputs.context }}/.dockerignore.bak"
        cp "${{ inputs.dockerignore_override }}" "${{ inputs.context }}/.dockerignore"

    - name: Build Docker image
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        docker buildx build \
          --tag ${{ inputs.registry_address }}/${{ inputs.app }}:${{ inputs.tag }} \
          --file ${{ inputs.dockerfile }} \
          ${{ inputs.context }} \
          ${{ inputs.args }}

    - name: Restore original .dockerignore
      if: inputs.dockerignore_override != ''
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: mv "${{ inputs.context }}/.dockerignore.bak" "${{ inputs.context }}/.dockerignore"

    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry_address }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}
        logout: false

    - name: Push image to registry
      shell: bash
      run: docker push "${{ inputs.registry_address }}/${{ inputs.app }}:${{ inputs.tag }}"
